### ISSUE TITLE
Installed this - how to use it ?

### ISSUE THREAD

**Issue by webiedesign** [vvraskin/google-reviews-jplugin#1]
I installed this, added the place id and the api key- I am unsure what to do now so it will display

**Comment by vvraskin** [comment]
Assuming you already enabled the plugin and tried to insert `{gr}{/gr}` within your page?
Do get any errors in your browsers console?

**Comment by webiedesign** [comment]
Thank you, I see now where this info is included in the readme. My apologies I could have sworn I read through everything
